title: My blog
author: Oleksandr Pysaryuk
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about learning GitHub

# social links
twitter_username: alexpysaryuk # DO NOT include the @ character, or else the build will fail!
github_username:  o-ndr # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima 
